version: 2
jobs:
  test:
    working_directory: ~/circle
    docker: &ecr_base_image
      - image: $AWS_ECR_ACCOUNT_URL
        aws_auth:
          aws_access_key_id: $AWS_ACCESS_KEY_ID
          aws_secret_access_key: $AWS_SECRET_ACCESS_KEY
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: make spec
          command: make spec
  build_and_deploy_to_test:
    working_directory: ~/circle/git/fb-user-datastore
    docker: *ecr_base_image
    steps:
      - checkout
      - setup_remote_docker
      - add_ssh_keys:
          fingerprints:
            - "9f:66:01:8b:19:3c:0e:40:6f:b8:e0:11:a4:43:09:af"
      - run:
          name: Setup base environment variable
          command: |
            echo "export BUILD_SHA=$CIRCLE_SHA1" >> $BASH_ENV
            echo "export SSH_FILE_FOR_SECRETS=~/.ssh/id_rsa_9f66018b193c0e406fb8e011a44309af" >> $BASH_ENV
      - run:
          name: cloning deploy scripts
          command: 'git clone git@github.com:ministryofjustice/fb-deploy.git deploy-scripts'
      - run:
          name: build and push docker images
          environment:
            ENVIRONMENT_NAME: test
          command: './deploy-scripts/bin/build'
      - run:
          name: deploy to test dev
          environment:
            APPLICATION_NAME: fb-user-datastore
            PLATFORM_ENV: test
            DEPLOYMENT_ENV: dev
            K8S_NAMESPACE: formbuilder-platform-test-dev
          command: './deploy-scripts/bin/deploy'
      - run:
          name: deploy to test production
          environment:
            APPLICATION_NAME: fb-user-datastore
            PLATFORM_ENV: test
            DEPLOYMENT_ENV: production
            K8S_NAMESPACE: formbuilder-platform-test-production
          command: './deploy-scripts/bin/deploy'
  build_and_deploy_to_live:
    working_directory: ~/circle/git/fb-user-datastore
    docker: *ecr_base_image
    steps:
      - checkout
      - setup_remote_docker
      - add_ssh_keys:
          fingerprints:
            - "9f:66:01:8b:19:3c:0e:40:6f:b8:e0:11:a4:43:09:af"
      - run:
          name: Setup base environment variable
          command: |
            echo "export BUILD_SHA=$CIRCLE_SHA1" >> $BASH_ENV
            echo "export SSH_FILE_FOR_SECRETS=~/.ssh/id_rsa_9f66018b193c0e406fb8e011a44309af" >> $BASH_ENV
      - run:
          name: cloning deploy scripts
          command: 'git clone git@github.com:ministryofjustice/fb-deploy.git deploy-scripts'
      - run:
          name: build and push docker images
          environment:
            ENVIRONMENT_NAME: live
          command: './deploy-scripts/bin/build'
      - run:
          name: deploy to live dev
          environment:
            APPLICATION_NAME: fb-user-datastore
            PLATFORM_ENV: live
            DEPLOYMENT_ENV: dev
            K8S_NAMESPACE: formbuilder-platform-live-dev
          command: './deploy-scripts/bin/deploy'
      - run:
          name: deploy to live production
          environment:
            APPLICATION_NAME: fb-user-datastore
            PLATFORM_ENV: live
            DEPLOYMENT_ENV: production
            K8S_NAMESPACE: formbuilder-platform-live-production
          command: './deploy-scripts/bin/deploy'
  trigger_acceptance_tests:
    working_directory: ~/circle/git/fb-user-datastore
    docker: *ecr_base_image
    steps:
      - add_ssh_keys:
          fingerprints:
            - "9f:66:01:8b:19:3c:0e:40:6f:b8:e0:11:a4:43:09:af"
      - run:
          name: cloning deploy scripts
          command: 'git clone git@github.com:ministryofjustice/fb-deploy.git deploy-scripts'
      - run:
          name: "Trigger Acceptance Tests"
          command: './deploy-scripts/bin/acceptance_tests'

workflows:
  version: 2
  test_and_build:
    jobs:
      - test
      - build_and_deploy_to_test:
          requires:
            - test
          filters:
            branches:
              only:
                - master
      - trigger_acceptance_tests:
          requires:
            - build_and_deploy_to_test
          filters:
            branches:
              only: master
      - confirm_live_deploy:
          type: approval
          requires:
            - trigger_acceptance_tests
      - build_and_deploy_to_live:
          requires:
            - confirm_live_deploy
