apiVersion: v1
kind: ConfigMap
metadata:
  name: fb-user-datastore-api-env-{{ .Values.environmentName }}
  namespace: formbuilder-platform-{{ .Values.environmentName }}
data:
  RAILS_ENV: "production"
  RAILS_SERVE_STATIC_FILES: "false"
  MAX_IAT_SKEW_SECONDS: "60"
  SERVICE_TOKEN_CACHE_ROOT_URL: "http://fb-service-token-cache-svc-{{ .Values.environmentName }}/"
  SUBMITTER_URL: "http://fb-submitter-api-svc-{{ .Values.environmentName }}"
  FORM_URL_SUFFIX: "{{ .Values.formUrlSuffix }}"
  RAILS_LOG_TO_STDOUT: "true"
