apiVersion: v1
kind: Secret
metadata:
  name: fb-user-datastore-api-secrets-{{ .Values.environmentName }}
type: Opaque
data:
  secret_key_base: {{ .Values.secret_key_base }}
---
apiVersion: v1
kind: Secret
metadata:
   name: fb-platform-datastore-token-{{ .Values.environmentName }}
   namespace: formbuilder-platform-{{ .Values.environmentName }}
 type: Opaque
 data:
   token: {{ .Values.service_token }}
